//LOCALHOST
### Get all students
GET http://localhost:3000/students

### Get contact by id
GET http://localhost:3000/students/682714c252d712e5160b7fd4 



### Create student
POST http://localhost:3000/students HTTP/1.1
content-type: application/json

{
"email": "miguel.gonzalez@example.com",
    "gradeLevel": "Senior",
    "major": "Computer Science",
    "gpa": 3.8,
    "enrollmentDate": "2023-08-15",
    "isActive": true,
    "firstName": "Sergio ",
    "lastName": "Gonzalez"


}


### Put student
PUT http://localhost:3000/students/682c5c3c4b8b0b72569608cc HTTP/1.1
content-type: application/json

{

  "firstName": "Sergio ",
    "lastName": "Gonzalez",
    "email": "serg.gonzalez@example.com",
    "gradeLevel": "Senior",
    "major": "Computer Science",
    "gpa": 3.8,
    "enrollmentDate": "2023-08-15",
    "isActive": true

}


### Delete student
DELETE http://localhost:3000/students/682c5c3c4b8b0b72569608cc HTTP/1.1
